### ISSUE TITLE
Использование enum - это очень здорово, но константам лучше дать развернутые имена

### ISSUE THREAD

**Issue by Shumakov** [Julia8Marchenko/DZ-29-10-24---#1]
https://github.com/Julia8Marchenko/DZ-29-10-24---/blob/dc81569f1a6497bc78877cf80c4fc0a20a1d7078/DZ%20%D0%BE%D1%82%2029-10-24%20%D0%9C%D0%B5%D0%BD%D1%8E%20-%20%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8%20%D0%B2%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B5/DZ%20%D0%BE%D1%82%2029-10-24%20%D0%9C%D0%B5%D0%BD%D1%8E%20-%20%D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D0%B8%20%D0%B2%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B5.cpp#L12

**Comment by Julia8Marchenko** [comment]
Константин, замечания учтены
